### ISSUE TITLE
Wrong order for video links

### ISSUE THREAD

**Issue by fenaux** [kaulquappe23/all-keypoints-jump-broadcast#1]
Thanks for this dataset.

I noticed there is a difference in the order of the titles in the file "video_indices.txt" and in the file "video_download_links.txt
there is also a typo in Zürich that appears as Zuerich.

I attache a file with the video links reordered
[corrected video links.ods](https://github.com/kaulquappe23/all-keypoints-jump-broadcast/files/11945987/corrected.video.links.ods)

**Comment by kaulquappe23** [comment]
The file was not meant to be ordered, but I fixed it now. A new version of the dataset is now available on the website.
