### ISSUE TITLE
annotations problem

### ISSUE THREAD

**Issue by fenaux** [kaulquappe23/all-keypoints-jump-broadcast#2]
Thanks to share your work and dataset.

In the video "12: Complete Men's Triple Jump Final.   Zuerich Diamond League, Day 2, Letzigrund, September 9, 2021.-I3a6zoiP2FY" it seems there is an offset between frame number and annotations

Here is the code I use to select the frame
`vid = imageio.get_reader(video_name,  'ffmpeg')`
`for frame, keys in zip(frames, keys_video):`
`      img = vid.get_data(frame)`

I did not notice such an offset in the previous video
![annotation offset](https://github.com/kaulquappe23/all-keypoints-jump-broadcast/assets/44709416/74358467-ee3d-4ed7-903c-9b91224ddbe1)

**Comment by kaulquappe23** [comment]
You are right, there was a constant offset in the video. I adjusted the annotations and created new segmentation masks for the correct frames. A new version of the dataset is now available on the website.
